//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchStudent
    {
        public int Id { get; set; }
        public Nullable<int> BatchId { get; set; }
        public Nullable<int> StudentId { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual Student Student { get; set; }
    }
}
